version: '2.2'

services:
  OcvSsdFaceDetection:
    cpuset: "0,1,2,3"
    #cpus: "1.0"
    image: openmpf/openmpf_cpp_component_dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MPF_LOG_PATH: .
      THIS_MPF_NODE: .
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../../..:/home/mpf/openmpf-components:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  default:
    external:
      name: localdev
